---
title: ""
author: ""
date: ""
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 3
    smooth_scroll: false
    theme: cerulean
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(reshape2)
library(tidyverse)
library(rtracklayer)
library(isoband)
library(sf)
library(MASS)
library(lwgeom)
library(ggrepel)
library(hexbin)
library(ggrastr)
library(viridis)
library(pals)
library(patchwork)
library(highcharter)
library(dplyr)
library(GenomicRanges)
library(reactable)
library(data.table)
#
library(DESeq2)
library(edgeR)
#
library(plotly)
#
library(TxDb.Hsapiens.UCSC.hg38.knownGene)
library(org.Hs.eg.db)
library(ChIPseeker)
#
library(gprofiler2)
library(clusterProfiler)
#
library(ChIPpeakAnno)
library(VennDiagram)
library(Vennerable)
#
library(pals)
library(highcharter)
library(plotly)
library(heatmaply)
# library(plotlyutils)
library(htmltools)
library(uwot)
library(smacof)
library(trelliscopejs)
#library(LOLA)
library(upsetjs)
library(jsonlite)
library(limma)
library(crosstalk)
library(DT)
#library(future)
#plan(multisession(workers = 16))
#library(furrr)
#library(future.apply)
#
txdb <- TxDb.Hsapiens.UCSC.hg38.knownGene
#
options(ChIPseeker.ignore_1st_exon = TRUE)
options(ChIPseeker.ignore_1st_intron = TRUE)
options(ChIPseeker.ignore_downstream = TRUE)
options(ChIPseeker.ignore_promoter_subcategory = TRUE)
```

```{r echo = FALSE, warning=FALSE,message=FALSE,out.width='100%'}
setwd("~/Documents/HNSCC_K36me2")
```

# K36me & K27me {.tabset}

## All
```{r echo = FALSE, warning=FALSE,message=FALSE,out.width='100%'}
# K36me and K27me
d <- fread("~/Documents/HNSCC_K36me2/data/ms.ratios/hnscc.ms.ratios.final.csv") %>%
  dplyr::slice(48:53) %>%
  pivot_longer(2:38)
d$value <- d$value*100
d$mark <- sub("final_","",d$mark)
# d$name <- sub("10T-","",d$name)
d$mark <- factor(d$mark,levels= c("H3K36me1","H3K36me2","H3K36me3","H3K27me1","H3K27me2","H3K27me3"))
# ggplot
ggplot(d,aes(x = name, y= value)) +
  geom_point(aes(color = name),show.legend = FALSE,size=1) +
  facet_wrap(. ~ mark,nrow = 2,scales = "free") +
  labs(y="% of peptides with modification",x="") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1,size=3.5))
```

## Cal27
```{r echo = FALSE, warning=FALSE,message=FALSE,out.width='100%'}
cal27 <- d[grep("Cal27",d$name),]
# ggplot
ggplot(cal27,aes(x = name, y= value)) +
  geom_point(aes(color = name),show.legend = FALSE) +
  facet_wrap(. ~ mark,nrow = 2,scales = "free") +
  labs(y="% of peptides with modification",x="") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1,size=5))
```

## Detroit
```{r echo = FALSE, warning=FALSE,message=FALSE,out.width='100%'}
detroit <- d[grep("Detroit562",d$name),]
# ggplot
ggplot(detroit,aes(x = name, y= value)) +
  geom_point(aes(color = name),show.legend = FALSE) +
  facet_wrap(. ~ mark,nrow = 2,scales = "free") +
  labs(y="% of peptides with modification",x="") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1,size=5))
```

## Fadu + others
```{r echo = FALSE, warning=FALSE,message=FALSE,out.width='100%'}
fadu <- d %>%
  dplyr::filter(!grepl('Detroit562',name)) %>%
  dplyr::filter(!grepl('Cal27',name))
# ggplot
ggplot(fadu,aes(x = name, y= value)) +
  geom_point(aes(color = name),show.legend = FALSE) +
  facet_wrap(. ~ mark,nrow = 2,scales = "free") +
  labs(y="% of peptides with modification",x="") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1,size=5))
```

# K4me and K9me {.tabset}

## All
```{r echo = FALSE, warning=FALSE,message=FALSE,out.width='100%'}
# K36me and K27me
d <- fread("~/Documents/HNSCC_K36me2/data/ms.ratios/hnscc.ms.ratios.final.csv") %>%
  dplyr::slice(c(1:3,5:7)) %>%
  pivot_longer(2:38)
d$value <- d$value*100
# d$name <- sub("10T-","",d$name)
d$mark <- factor(d$mark,levels= c("H3K4me1","H3K4me2","H3K4me3","H3K9me1","H3K9me2","H3K9me3"))
# ggplot
ggplot(d,aes(x = name, y= value)) +
  geom_point(aes(color = name),show.legend = FALSE,size=1) +
  facet_wrap(. ~ mark,nrow = 2,scales = "free") +
  labs(y="% of peptides with modification",x="") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1,size = 5))
```

## Cal27
```{r echo = FALSE, warning=FALSE,message=FALSE,out.width='100%'}
cal27 <- d[grep("Cal27",d$name),]
# ggplot
ggplot(cal27,aes(x = name, y= value)) +
  geom_point(aes(color = name),show.legend = FALSE) +
  facet_wrap(. ~ mark,nrow = 2,scales = "free") +
  labs(y="% of peptides with modification",x="") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1,size=5))
```

## Detroit
```{r echo = FALSE, warning=FALSE,message=FALSE,out.width='100%'}
detroit <- d[grep("Detroit562",d$name),]
# ggplot
ggplot(detroit,aes(x = name, y= value)) +
  geom_point(aes(color = name),show.legend = FALSE) +
  facet_wrap(. ~ mark,nrow = 2,scales = "free") +
  labs(y="% of peptides with modification",x="") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1,size=5))
```

## Fadu + others
```{r echo = FALSE, warning=FALSE,message=FALSE,out.width='100%'}
fadu <- d %>%
  dplyr::filter(!grepl('Detroit562',name)) %>%
  dplyr::filter(!grepl('Cal27',name))
# ggplot
ggplot(fadu,aes(x = name, y= value)) +
  geom_point(aes(color = name),show.legend = FALSE) +
  facet_wrap(. ~ mark,nrow = 2,scales = "free") +
  labs(y="% of peptides with modification",x="") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1,size=5))
```